/* Auto-generated by AuthSystem - 2026-03-01T04:43:45.957Z */
// Public configuration for auth forms
// These values are embedded at build time
// The forms call the public API (Netlify Functions), not Supabase directly

export const config = {
  apiBaseUrl: '/api', // Uses Netlify redirect from netlify.toml
  appId: 'app_804b6704-24a',
  apiKey: 'ak_production_884f84ff20faa2c3da8ba128323a8047'
};
