/* Auto-generated by AuthSystem - 2026-03-03T02:24:28.557Z */
// Public configuration for auth forms
// These values are embedded at build time
// The forms call the public API (Netlify Functions), not Supabase directly

export const config = {
  apiBaseUrl: '/api', // Uses Netlify redirect from netlify.toml
  appId: 'app_b9b5f22b-cda',
  apiKey: 'ak_production_250833639fd9039f78830df4246f9673'
};
