/* Auto-generated by AuthSystem - 2026-03-02T03:43:41.932Z */
// Public configuration for auth forms
// These values are embedded at build time
// The forms call the public API (Netlify Functions), not Supabase directly

export const config = {
  apiBaseUrl: '/api', // Uses Netlify redirect from netlify.toml
  appId: 'app_a6f840c5-bd1',
  apiKey: 'ak_production_b6ea163e30e60b62dda0909755a4a4c6'
};
