/* Auto-generated by AuthSystem - 2026-03-01T04:59:11.650Z */
import { createClient } from '@supabase/supabase-js';

// Supabase client for public read-only access to branding data
const supabaseUrl = 'https://sfqtmnncgiqkveaoqckt.supabase.co';
const supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNmcXRtbm5jZ2lxa3ZlYW9xY2t0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk4MDEyNDMsImV4cCI6MjA3NTM3NzI0M30.n2yaYrfHDLAFePP1tA3-250P6bgKmf696fYJFHfRZaQ';

export const supabase = createClient(supabaseUrl, supabaseAnonKey);
